// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RezervasyonMvc.DataAccess.Concrete;

namespace RezervasyonMvc.DataAccess.Migrations
{
    [DbContext(typeof(RezervasyonContext))]
    [Migration("20221221233759_tableMigration")]
    partial class tableMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RezervasyonMvc.Model.Models.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MusteriAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriSoyadi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TcNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.Oda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("OdaFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OdaKapasite")
                        .HasColumnType("int");

                    b.Property<string>("OdaNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YatakSayısı")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Odalar");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.Rezervasyon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CikisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GrisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("KişiSayisi")
                        .HasColumnType("int");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<int>("OdaSayisi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.ToTable("Rezervasyonlar");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.RezervasyonHareket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GunSayisi")
                        .HasColumnType("int");

                    b.Property<int>("KisiSayisi")
                        .HasColumnType("int");

                    b.Property<int>("OdaId")
                        .HasColumnType("int");

                    b.Property<int>("RezervasyonId")
                        .HasColumnType("int");

                    b.Property<decimal>("ToplamOdaFiyati")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("YatakSayisi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OdaId");

                    b.HasIndex("RezervasyonId");

                    b.ToTable("RezervasyonHareketleri");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.Rezervasyon", b =>
                {
                    b.HasOne("RezervasyonMvc.Model.Models.Musteri", "Musteri")
                        .WithMany("Rezervasyonlar")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.RezervasyonHareket", b =>
                {
                    b.HasOne("RezervasyonMvc.Model.Models.Oda", "Oda")
                        .WithMany("RezervasyonHareketleri")
                        .HasForeignKey("OdaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RezervasyonMvc.Model.Models.Rezervasyon", "Rezervasyon")
                        .WithMany("RezervasyonHareketleri")
                        .HasForeignKey("RezervasyonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oda");

                    b.Navigation("Rezervasyon");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.Musteri", b =>
                {
                    b.Navigation("Rezervasyonlar");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.Oda", b =>
                {
                    b.Navigation("RezervasyonHareketleri");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.Rezervasyon", b =>
                {
                    b.Navigation("RezervasyonHareketleri");
                });
#pragma warning restore 612, 618
        }
    }
}
