// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RezervasyonMvc.DataAccess.Concrete;

namespace RezervasyonMvc.DataAccess.Migrations
{
    [DbContext(typeof(RezervasyonContext))]
    [Migration("20221226020615_denemee")]
    partial class denemee
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RezervasyonMvc.Model.Models.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresi")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Adresi");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MusteriAdi")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("MusteriAdi");

                    b.Property<string>("MusteriSoyadi")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("MusteriSoyadi");

                    b.Property<string>("TcNo")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("TcNo");

                    b.HasKey("Id");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.Oda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("OdaFiyat")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("OdaFiyat");

                    b.Property<int>("OdaKapasite")
                        .HasColumnType("int")
                        .HasColumnName("OdaKapasite");

                    b.Property<string>("OdaNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("OdaNo");

                    b.Property<bool>("Rezerve")
                        .HasColumnType("bit")
                        .HasColumnName("Rezerve");

                    b.Property<int>("YatakSayısı")
                        .HasColumnType("int")
                        .HasColumnName("YatakSayısı");

                    b.HasKey("Id");

                    b.ToTable("Odalar");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.Rezervasyon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CikisTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("CikisTarihi");

                    b.Property<DateTime>("GrisTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("GrisTarihi");

                    b.Property<int>("GunSayisi")
                        .HasColumnType("int");

                    b.Property<int>("KisiSayisi")
                        .HasColumnType("int")
                        .HasColumnName("KisiSayisi");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int")
                        .HasColumnName("MusteriId");

                    b.Property<int>("OdaSayisi")
                        .HasColumnType("int")
                        .HasColumnName("OdaSayisi");

                    b.Property<decimal>("RezToplamTutar")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("RezToplamTutar");

                    b.Property<int>("YatakSayisi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.ToTable("Rezervasyonlar");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.Rezervasyon", b =>
                {
                    b.HasOne("RezervasyonMvc.Model.Models.Musteri", "Musteri")
                        .WithMany("Rezervasyonlar")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.Musteri", b =>
                {
                    b.Navigation("Rezervasyonlar");
                });
#pragma warning restore 612, 618
        }
    }
}
