// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RezervasyonMvc.DataAccess.Concrete;

namespace RezervasyonMvc.DataAccess.Migrations
{
    [DbContext(typeof(RezervasyonContext))]
    [Migration("20230103030855_yeniMg")]
    partial class yeniMg
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RezervasyonMvc.Model.Models.Banka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bankasi")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Bankasi");

                    b.Property<string>("HesapIsmi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HesapIsmi");

                    b.Property<string>("HesapKodu")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("HesapKodu");

                    b.Property<string>("HesapNo")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("HesapNo");

                    b.Property<string>("IbanNo")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)")
                        .HasColumnName("IbanNo");

                    b.Property<string>("Sube")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Sube");

                    b.Property<string>("YetkiliAdi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("YetkiliAdi");

                    b.Property<string>("YetkiliTelefonu")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("YetkiliTelefonu");

                    b.HasKey("Id");

                    b.ToTable("Bankalar");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.BankaHareket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Aciklama");

                    b.Property<int>("BankaId")
                        .HasColumnType("int")
                        .HasColumnName("BankaId");

                    b.Property<int?>("CariId")
                        .HasColumnType("int")
                        .HasColumnName("CariId");

                    b.Property<string>("FisKodu")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("FisKodu");

                    b.Property<string>("Hareket")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Hareket");

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("datetime2")
                        .HasColumnName("Tarih");

                    b.Property<decimal?>("Tutar")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("Tutar");

                    b.HasKey("Id");

                    b.HasIndex("BankaId");

                    b.HasIndex("CariId");

                    b.ToTable("BankaHareketleri");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.Cari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Aciklama");

                    b.Property<string>("Adres")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Adres");

                    b.Property<string>("AlisOzelFiyati")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("AlisOzelFiyati");

                    b.Property<string>("CariAdi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CariAdi");

                    b.Property<string>("CariAltGrubu")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("CariAltGrubu");

                    b.Property<string>("CariGrubu")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("CariGrubu");

                    b.Property<string>("CariKodu")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("CariKodu");

                    b.Property<string>("CariTuru")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("CariTuru");

                    b.Property<string>("CepTelefonu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CepTelefonu");

                    b.Property<bool>("Durumu")
                        .HasColumnType("bit")
                        .HasColumnName("Durumu");

                    b.Property<string>("EMail")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EMail");

                    b.Property<string>("FaturaUnvani")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FaturaUnvani");

                    b.Property<string>("Fax")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Fax");

                    b.Property<string>("Il")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Il");

                    b.Property<string>("Ilce")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Ilce");

                    b.Property<decimal?>("IskontoOrani")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("IskontoOrani");

                    b.Property<string>("OzelKod1")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("OzelKod1");

                    b.Property<string>("OzelKod2")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("OzelKod2");

                    b.Property<string>("OzelKod3")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("OzelKod3");

                    b.Property<string>("OzelKod4")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("OzelKod4");

                    b.Property<decimal?>("RiskLimiti")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("RiskLimiti");

                    b.Property<string>("SatisOzelFiyati")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SatisOzelFiyati");

                    b.Property<string>("Semt")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Semt");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Telefon");

                    b.Property<string>("VergiDairesi")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("VergiDairesi");

                    b.Property<string>("VergiNo")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("VergiNo");

                    b.Property<string>("Web")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("YetkiliKisi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("YetkiliKisi");

                    b.HasKey("Id");

                    b.ToTable("Cariler");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.Depo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Aciklama");

                    b.Property<string>("Adres")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Adres");

                    b.Property<string>("DepoAdi")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("DepoAdi");

                    b.Property<string>("DepoKodu")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("DepoKodu");

                    b.Property<string>("Il")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Il");

                    b.Property<string>("Ilce")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Ilce");

                    b.Property<string>("Semt")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Semt");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Telefon");

                    b.Property<string>("YetkiliAdi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("YetkiliAdi");

                    b.Property<string>("YetkiliKodu")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("YetkiliKodu");

                    b.HasKey("Id");

                    b.ToTable("Depolar");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.Fis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Aciklama");

                    b.Property<string>("Adres")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Adres");

                    b.Property<decimal?>("Alacak")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("Alacak");

                    b.Property<int?>("BankaId")
                        .HasColumnType("int")
                        .HasColumnName("BankaId");

                    b.Property<string>("BelgeNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("BelgeNo");

                    b.Property<decimal?>("Borc")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("Borc");

                    b.Property<int?>("CariId")
                        .HasColumnType("int")
                        .HasColumnName("CariId");

                    b.Property<string>("CariTuru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CepTelefonu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CepTelefonu");

                    b.Property<string>("DepoAdi")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("DepoAdi");

                    b.Property<bool>("DepoIrsaliye")
                        .HasColumnType("bit");

                    b.Property<string>("FaturaUnvani")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FaturaUnvani");

                    b.Property<string>("FisBaglantiKodu")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("FisBaglantiKodu");

                    b.Property<string>("FisKodu")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("FisKodu");

                    b.Property<string>("FisTuru")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("FisTuru");

                    b.Property<string>("Il")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Il");

                    b.Property<string>("Ilce")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Ilce");

                    b.Property<decimal?>("IskontoOrani")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("IskontoOrani");

                    b.Property<decimal?>("IskontoTutar")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("IskontoTutar");

                    b.Property<int?>("PlasiyerId")
                        .HasColumnType("int")
                        .HasColumnName("PlasiyerId");

                    b.Property<string>("Semt")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Semt");

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("datetime2")
                        .HasColumnName("Tarih");

                    b.Property<decimal?>("ToplamTutar")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("ToplamTutar");

                    b.Property<string>("VergiDairesi")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("VergiDairesi");

                    b.Property<string>("VergiNo")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("VergiNo");

                    b.HasKey("Id");

                    b.HasIndex("BankaId");

                    b.HasIndex("CariId");

                    b.HasIndex("PlasiyerId");

                    b.ToTable("Fisler");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.HizliSatis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Barkod")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Barkod");

                    b.Property<int>("GrupId")
                        .HasColumnType("int");

                    b.Property<string>("UrunAdi")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("UrunAdi");

                    b.HasKey("Id");

                    b.ToTable("HizliSatislar");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.HizliSatisGrup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Aciklama");

                    b.Property<string>("GrupAdi")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("GrupAdi");

                    b.HasKey("Id");

                    b.ToTable("HizliSatislarGruplari");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.Indirim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Aciklama");

                    b.Property<string>("Barkod")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Barkod");

                    b.Property<DateTime?>("BaslangicTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("BaslangicTarihi");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("BitisTarihi");

                    b.Property<bool>("Durumu")
                        .HasColumnType("bit")
                        .HasColumnName("Durumu");

                    b.Property<decimal>("IndirimOrani")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("IndirimOrani");

                    b.Property<string>("IndirimTuru")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("IndirimTuru");

                    b.Property<string>("StokAdi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("StokAdi");

                    b.Property<string>("StokKodu")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("StokKodu");

                    b.HasKey("Id");

                    b.ToTable("Indirimler");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.Kasa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Aciklama");

                    b.Property<string>("KasaAdi")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("KasaAdi");

                    b.Property<string>("KasaKodu")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("KasaKodu");

                    b.Property<string>("YetkiliAdi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("YetkiliAdi");

                    b.Property<string>("YetkiliKodu")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("YetkiliKodu");

                    b.HasKey("Id");

                    b.ToTable("Kasalar");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.KasaHareket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Aciklama");

                    b.Property<int?>("CariId")
                        .HasColumnType("int")
                        .HasColumnName("CariId");

                    b.Property<string>("FisKodu")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("FisKodu");

                    b.Property<string>("Hareket")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Hareket");

                    b.Property<int>("KasaId")
                        .HasColumnType("int")
                        .HasColumnName("KasaId");

                    b.Property<int>("OdemeTuruId")
                        .HasColumnType("int")
                        .HasColumnName("OdemeTuruId");

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("datetime2")
                        .HasColumnName("Tarih");

                    b.Property<decimal?>("Tutar")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("Tutar");

                    b.HasKey("Id");

                    b.HasIndex("CariId");

                    b.HasIndex("KasaId");

                    b.HasIndex("OdemeTuruId");

                    b.ToTable("KasaHareketleri");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.Kod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OnEki")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("OnEki");

                    b.Property<int>("SonDeger")
                        .HasColumnType("int")
                        .HasColumnName("SonDeger");

                    b.Property<string>("Tablo")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("Tablo");

                    b.HasKey("Id");

                    b.ToTable("Kodlar");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Adi");

                    b.Property<string>("Cevap")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Cevap");

                    b.Property<string>("Gorevi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Gorevi");

                    b.Property<string>("HatirlatmaSorusu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HatirlatmaSorusu");

                    b.Property<DateTime?>("KayitTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("KayitTarihi");

                    b.Property<string>("KullaniciAdi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("KullaniciAdi");

                    b.Property<string>("Parola")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("Parola");

                    b.Property<DateTime?>("SonGirisTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("SonGirisTarihi");

                    b.Property<string>("Soyadi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Soyadi");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.KullaniciRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FormAdi")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)")
                        .HasColumnName("FormAdi");

                    b.Property<string>("KontrolAdi")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)")
                        .HasColumnName("KontrolAdi");

                    b.Property<string>("KullaniciAdi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("KullaniciAdi");

                    b.Property<int>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("ParentId");

                    b.Property<int>("RootId")
                        .HasColumnType("int")
                        .HasColumnName("RootId");

                    b.Property<bool>("Yetki")
                        .HasColumnType("bit")
                        .HasColumnName("Yetki");

                    b.HasKey("Id");

                    b.ToTable("KullaniciRolleri");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.OdemeTuru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Aciklama");

                    b.Property<string>("OdemeTuruAdi")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("OdemeTuruAdi");

                    b.Property<string>("OdemeTuruKodu")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("OdemeTuruKodu");

                    b.HasKey("Id");

                    b.ToTable("OdemeTurleri");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Aciklama");

                    b.Property<string>("Adres")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Adres");

                    b.Property<decimal?>("AylikMaasi")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("AylikMaasi");

                    b.Property<bool>("Calisiyor")
                        .HasColumnType("bit")
                        .HasColumnName("Calisiyor");

                    b.Property<string>("CepTelefonu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CepTelefonu");

                    b.Property<string>("EMail")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EMail");

                    b.Property<string>("Fax")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Fax");

                    b.Property<string>("Il")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Il");

                    b.Property<string>("Ilce")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Ilce");

                    b.Property<DateTime?>("IseGirisTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("IseGirisTarihi");

                    b.Property<DateTime?>("IstenCikisTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("IstenCikisTarihi");

                    b.Property<string>("PersonelAdi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PersonelAdi");

                    b.Property<string>("PersonelKodu")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("PersonelKodu");

                    b.Property<decimal?>("PrimOrani")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("PrimOrani");

                    b.Property<string>("Semt")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Semt");

                    b.Property<string>("TcKimlikNo")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("TcKimlikNo");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Telefon");

                    b.Property<string>("Unvani")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("Unvani");

                    b.Property<string>("VergiDairesi")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("VergiDairesi");

                    b.Property<string>("VergiNo")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("VergiNo");

                    b.Property<string>("Web")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Web");

                    b.HasKey("Id");

                    b.ToTable("Personeller");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.PersonelHareket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Aciklama");

                    b.Property<decimal>("AylikMaasi")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("AylikMaasi");

                    b.Property<DateTime>("Donemi")
                        .HasColumnType("datetime2")
                        .HasColumnName("Donemi");

                    b.Property<string>("FisKodu")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("FisKodu");

                    b.Property<string>("PersonelAdi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PersonelAdi");

                    b.Property<string>("PersonelKodu")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("PersonelKodu");

                    b.Property<decimal>("PrimOrani")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("PrimOrani");

                    b.Property<string>("TcKimlikNo")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("TcKimlikNo");

                    b.Property<decimal>("ToplamSatis")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("ToplamSatis");

                    b.Property<string>("Unvani")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("Unvani");

                    b.HasKey("Id");

                    b.ToTable("PersonelHareketleri");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.SirketBilgi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Aciklama");

                    b.Property<string>("Adres")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Adres");

                    b.Property<string>("EMail")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EMail");

                    b.Property<string>("Fax")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Fax");

                    b.Property<string>("Ilcesi")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Ilcesi");

                    b.Property<string>("Ili")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Ili");

                    b.Property<string>("Semt")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Semt");

                    b.Property<string>("SirketKisaAdi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SirketKisaAdi");

                    b.Property<string>("SirketKodu")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("SirketKodu");

                    b.Property<string>("SirketTelNo")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("SirketTelNo");

                    b.Property<string>("SirketUnvani")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("SirketUnvani");

                    b.Property<string>("Ulkesi")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Ulkesi");

                    b.Property<string>("VergiDairesi")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("VergiDairesi");

                    b.Property<string>("VergiNo")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("VergiNo");

                    b.Property<string>("Web")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Web");

                    b.Property<string>("YetkiliKisi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("YetkiliKisi");

                    b.HasKey("Id");

                    b.ToTable("SirketBilgileri");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.Stok", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Aciklama");

                    b.Property<decimal?>("AlisFiyati1")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("AlisFiyati1");

                    b.Property<decimal?>("AlisFiyati2")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("AlisFiyati2");

                    b.Property<decimal?>("AlisFiyati3")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("AlisFiyati3");

                    b.Property<int>("AlisKdv")
                        .HasColumnType("int")
                        .HasColumnName("AlisKdv");

                    b.Property<string>("Barkod")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Barkod");

                    b.Property<string>("BarkodTuru")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("BarkodTuru");

                    b.Property<string>("Birimi")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("Birimi");

                    b.Property<bool>("Durumu")
                        .HasColumnType("bit")
                        .HasColumnName("Durumu");

                    b.Property<string>("GarantiSuresi")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("GarantiSüresi");

                    b.Property<string>("Gorsel")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Gorsel");

                    b.Property<string>("Marka")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Marka");

                    b.Property<decimal?>("MaxStokMiktari")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("MaxStokMiktari");

                    b.Property<decimal?>("MinStokMiktari")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("MinStokMiktari");

                    b.Property<string>("Modeli")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Modeli");

                    b.Property<string>("OzelKod1")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("OzelKod1");

                    b.Property<string>("OzelKod2")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("OzelKod2");

                    b.Property<string>("OzelKod3")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("OzelKod3");

                    b.Property<string>("OzelKod4")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("OzelKod4");

                    b.Property<decimal?>("SatisFiyati1")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("SatisFiyati1");

                    b.Property<decimal?>("SatisFiyati2")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("SatisFiyati2");

                    b.Property<decimal?>("SatisFiyati3")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("SatisFiyati3");

                    b.Property<int>("SatisKdv")
                        .HasColumnType("int")
                        .HasColumnName("SatisKdv");

                    b.Property<string>("StokAdi")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("StokAdi");

                    b.Property<string>("StokAltGrubu")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("StokAltGrubu");

                    b.Property<string>("StokGrubu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("StokGrubu");

                    b.Property<string>("StokKodu")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)")
                        .HasColumnName("StokKodu");

                    b.Property<string>("UreticiKodu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("UreticiKodu");

                    b.HasKey("Id");

                    b.ToTable("Stoklar");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.StokHareket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Aciklama");

                    b.Property<decimal?>("AlisFiyati")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("AlisFiyati");

                    b.Property<decimal?>("AlisFiyati2")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("AlisFiyati2");

                    b.Property<decimal?>("AlisFiyati3")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("AlisFiyati3");

                    b.Property<decimal?>("BirimFiyati")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("BirimFiyati");

                    b.Property<int>("DepoId")
                        .HasColumnType("int")
                        .HasColumnName("DepoId");

                    b.Property<string>("FisBaglantiKodu")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("FisBaglantiKodu");

                    b.Property<string>("FisKodu")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("FisKodu");

                    b.Property<string>("Hareket")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Hareket");

                    b.Property<decimal?>("IndirimOrani")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("IndirimOrani");

                    b.Property<bool>("Irsaliye")
                        .HasColumnType("bit");

                    b.Property<int>("Kdv")
                        .HasColumnType("int")
                        .HasColumnName("Kdv");

                    b.Property<decimal?>("MevcutStok")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("MevcutStok");

                    b.Property<decimal?>("Miktar")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)");

                    b.Property<decimal?>("SayimMiktari")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("SayimMiktari");

                    b.Property<string>("SeriNo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SeriNo");

                    b.Property<bool>("Siparis")
                        .HasColumnType("bit");

                    b.Property<int>("StokId")
                        .HasColumnType("int")
                        .HasColumnName("StokId");

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("datetime2")
                        .HasColumnName("Tarih");

                    b.Property<bool>("Teklif")
                        .HasColumnType("bit");

                    b.Property<decimal?>("ToplamTutar")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("ToplamTutar");

                    b.HasKey("Id");

                    b.HasIndex("DepoId");

                    b.HasIndex("StokId");

                    b.ToTable("StokHareketleri");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.Tanim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Aciklama");

                    b.Property<string>("Tanimi")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Tanimi");

                    b.Property<string>("Turu")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("Turu");

                    b.HasKey("Id");

                    b.ToTable("Tanimlar");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.BankaHareket", b =>
                {
                    b.HasOne("RezervasyonMvc.Model.Models.Banka", "Banka")
                        .WithMany("BankaHareket")
                        .HasForeignKey("BankaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RezervasyonMvc.Model.Models.Cari", "Cari")
                        .WithMany("BankaHareket")
                        .HasForeignKey("CariId");

                    b.Navigation("Banka");

                    b.Navigation("Cari");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.Fis", b =>
                {
                    b.HasOne("RezervasyonMvc.Model.Models.Banka", "banka")
                        .WithMany("Fis")
                        .HasForeignKey("BankaId");

                    b.HasOne("RezervasyonMvc.Model.Models.Cari", "Cari")
                        .WithMany("Fis")
                        .HasForeignKey("CariId");

                    b.HasOne("RezervasyonMvc.Model.Models.Personel", "Personel")
                        .WithMany("Fis")
                        .HasForeignKey("PlasiyerId");

                    b.Navigation("banka");

                    b.Navigation("Cari");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.KasaHareket", b =>
                {
                    b.HasOne("RezervasyonMvc.Model.Models.Cari", "Cari")
                        .WithMany("KasaHareket")
                        .HasForeignKey("CariId");

                    b.HasOne("RezervasyonMvc.Model.Models.Kasa", "Kasa")
                        .WithMany("KasaHareket")
                        .HasForeignKey("KasaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RezervasyonMvc.Model.Models.OdemeTuru", "OdemeTuru")
                        .WithMany("KasaHareket")
                        .HasForeignKey("OdemeTuruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cari");

                    b.Navigation("Kasa");

                    b.Navigation("OdemeTuru");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.StokHareket", b =>
                {
                    b.HasOne("RezervasyonMvc.Model.Models.Depo", "Depo")
                        .WithMany("StokHareket")
                        .HasForeignKey("DepoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RezervasyonMvc.Model.Models.Stok", "Stok")
                        .WithMany("StokHareket")
                        .HasForeignKey("StokId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Depo");

                    b.Navigation("Stok");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.Banka", b =>
                {
                    b.Navigation("BankaHareket");

                    b.Navigation("Fis");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.Cari", b =>
                {
                    b.Navigation("BankaHareket");

                    b.Navigation("Fis");

                    b.Navigation("KasaHareket");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.Depo", b =>
                {
                    b.Navigation("StokHareket");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.Kasa", b =>
                {
                    b.Navigation("KasaHareket");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.OdemeTuru", b =>
                {
                    b.Navigation("KasaHareket");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.Personel", b =>
                {
                    b.Navigation("Fis");
                });

            modelBuilder.Entity("RezervasyonMvc.Model.Models.Stok", b =>
                {
                    b.Navigation("StokHareket");
                });
#pragma warning restore 612, 618
        }
    }
}
